### ISSUE TITLE
[bug report] No module named 'ldm_patched.ldm.models'

### ISSUE THREAD

**Issue by OnlyblackTea** [mrhan1993/ComfyUI-Fooocus#1]
https://github.com/mrhan1993/ComfyUI-Fooocus/blame/1b711f7dc90c3a0ddce2fb67c7bf885ed0838d21/ldm_patched/modules/sd.py#L4

This line imported a module that doesn't exist.

**Comment by OnlyblackTea** [comment]
also happens:
```
from apis.models.requests import (
    CommonRequest,
    ImagePrompt,
    EnhanceCtrlNets,
    Lora
)
ModuleNotFoundError: No module named 'apis.models'
```

**Comment by OnlyblackTea** [comment]
我尝试从[FooocusAPI](https://github.com/mrhan1993/FooocusAPI.git)拷贝了几个相关文件过来，临时解决了这个问题。

**Comment by mrhan1993** [comment]
嗯。。文件传少了，.gitignore 超范围了。。
